name: Robo PROMOREAIS
on:
  workflow_dispatch:

jobs:
  postar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Buscar Produto
        run: node atualizar_ofertas.js

      - name: Enviar
        env:
          TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          # Pega os dados do arquivo gerado pelo JS
          TITULO=$(node -e "console.log(require('./temp_oferta.json').titulo)")
          PRECO=$(node -e "console.log(require('./temp_oferta.json').preco)")
          LINK=$(node -e "console.log(require('./temp_oferta.json').link)")
          IMG=$(node -e "console.log(require('./temp_oferta.json').img)")

          # Envio direto (Igual ao que você fez no navegador)
          curl -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
            -d chat_id="$CHAT_ID" \
            -d text="🟡 ${TITULO}%0A💰 R$ ${PRECO}%0A%0A🛒 Link: ${LINK}"
